name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  RSPEC:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: blog_test
          POSTGRES_PASSWORD: 123123123
          POSTGRES_USER: rails
    env:
      RAILS_ENV: test
      POSTGRES_PASSWORD: 123123123
      POSTGRES_USER: rails
      POSTGRES_HOST: localhost
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Set up database schema
        run: bin/rails db:setup
      - name: Run tests
        run: bin/rake

  RUBOCOP:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
